language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: AjxZdDSzpfb51D2x1i94eOeToFenBDl620gSm36D9UWNzOHIbh2JLbmgWns4Bl8sQwUqElC0mVCtz6/y8tAHWmIK93b7evjvzSe6S85o6Tye27eK0OCaobgNqJY1jb6euBKIgWqKDoh7v0nbDolJwca7BgK5tUK1JUmuqRL0D5w985A1QlAXxBLVZKBqRLe9+9c/NPrjgTo8OICeUNbPMiRV9mp6Kh4Oys9pPYIGqCpudxTaQZXpRK2NYPqFdP7vJ6yIasqoo0HU1WkaLsUyLqc3Ts0NppFfEFYm0JMgN9mlOl8rKAa9ysK9EBJXmV5+MWSl1lHd+t4Q7uAow4vAQ4OQ8ySgfOBwfntbiG08UpkR5jnj3nwD4bSoryueKufXrZz/utbVt1cIjPjQymNE+AcNLHtvUWSTu9PBX7DnCWYavnmRtJBfDam2MOzwFyYBDdYeS4mtC+zxOoulhbrIo3NY1pXgDomNA7b66Qhwl3EbGVj5Z1w1s7sz/ouFgD8wDV1B9RJvPnDweDs5KNMPCCBiz8aYJzhKXV2uwKM/Bt4bqI1PDPr26Ak2stbtywwhpwF06tN/fufGjMXE1wxe8T0bsN+0VB5F+gmfY8JlKa/sj18Q3eO3gH2IqDfEu2Qlh59DoZVNt+whpEu8FNSljW+AN+HYHLw2j97U4VKRWdY=
  app: mrw-bot
cache:
  directories:
  - node_modules
